using System;
using System.Collections.Generic;
using System.Text;
using VideoOS.Platform;
using VideoOS.Platform.Client;
using VideoOS.Platform.Messaging;

namespace ControllerMonitor.Client
{
    /// <summary>
    /// This template code should be replaced with your code.
    /// 
    /// The UserControl to be displayed in a side panel in the Smart Client.<br/>
    /// Generated by a plug-ins SidePanelPlugin.
    /// </summary>
    public partial class ControllerMonitorSidePanelUserControl : SidePanelUserControl
    {

        public ControllerMonitorSidePanelUserControl()
        {
            InitializeComponent();
        }

        public override void Init()
        {
        }
        public override void Close()
        {
        }


        /// <summary>
        /// Sample code to show how to restore the view to normal mode, e.g. show all view items.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void OnRestoreClick(object sender, EventArgs e)
        {
            EnvironmentManager.Instance.SendMessage(
                new VideoOS.Platform.Messaging.Message(MessageId.SmartClient.ViewItemControlCommand)
                { Data = ViewItemControlCommandData.RestoreSelectedViewItem });
        }

        /// <summary>
        /// Sample code to show how to maximize the current view item to fill the entire layout area.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void OnMaximizeClick(object sender, EventArgs e)
        {
            EnvironmentManager.Instance.SendMessage(
                new VideoOS.Platform.Messaging.Message(MessageId.SmartClient.ViewItemControlCommand)
                { Data = ViewItemControlCommandData.MaximizeSelectedViewItem });
        }
    }
}
